### ISSUE TITLE
Error when using check_elasticsearch_shard.py

### ISSUE THREAD

**Issue by metabsd** [DennyZhang/elasticsearch-cli-tool#1]
First, thank you for sharing your great work :+1: 
Command I use : `./check_elasticsearch_shard.py --es_host myserver`
```
Traceback (most recent call last):
  File "./check_elasticsearch_shard.py", line 141, in <module>
    failed_index_list = confirm_es_shard_count(es_host, es_port, es_index_list, min_shard_count)
  File "./check_elasticsearch_shard.py", line 86, in confirm_es_shard_count
    number_of_shards = int(l[1])
ValueError: invalid literal for int() with base 10: 'FtFUCDQISjSkDOOdUJVTqg'
```

**Comment by dennyzhang** [comment]
@metabsd 

Thanks for filing the ticket.

Could you post the output of this command:
```curl $es_ip:$es_port/_cat/indices?v```

Slack brings people closer. 

We have an active Slack group, and #opensource channel is created for this kind of supports.

Do you want to join?

Feel free to skip, if you're too busy.

Slack link: https://goo.gl/ozDDyL
